---
- name: Wdrożenie podstawowej infrastruktury i DNS na AlmaLinux
  hosts: core_nodes
  become: true

  roles:
    - docker
    - blocky
    - portfolio
    - camera_wall
    - caddy
    - monitoring
    - vaultwarden
    - homepage
    - go2rtc
    - cloudflared
