# Multi-stage build: Compiling Caddy with the cloudflare DNS plugin
FROM caddy:{{ caddy_version }}-builder AS builder

RUN xcaddy build \
    --with github.com/caddy-dns/cloudflare

FROM caddy:{{ caddy_version }}-alpine

COPY --from=builder /usr/bin/caddy /usr/bin/caddy
