---
driver:
  name: docker

platforms:
  - name: portfolio-alma9
    image: almalinux:9
    pre_build_image: true

provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: auto_silent
  env:
    ANSIBLE_ROLES_PATH: ${MOLECULE_PROJECT_DIRECTORY}/..
  inventory:
    host_vars:
      portfolio-alma9:
        ansible_become: false

verifier:
  name: ansible
